git:
  depth: 3

osx_image: xcode10.2
language: swift
os: osx
xcode_project: FootballGather/FootballGather.xcodeproj
xcode_scheme: FootballGather-ci
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone XR
before_deploy: ./start-wiremock.sh
after_deploy: ./stop-wiremock.sh
