osx_image: xcode11.6
language: swift
install:
  - cd FootballGather
  - bundle install
  - gem update fastlane
before_script: ./../scripts/start-wiremock.sh
script:
  - fastlane ci_ut
after_script: ./../scripts/stop-wiremock.sh
